name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.8.0
homepage: https://github.com/fluttercommunity/chewie
publish_to: https://dart.cloudsmith.io/seadev-studios-gmbh/seadev/

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  provider: ^6.0.5
  video_player:
    version: ^2.9.0
    hosted:
      name: video_player
      url: https://dart.cloudsmith.io/seadev-studios-gmbh/seadev/
  wakelock_plus: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
